# -*- coding: utf-8 -*-
"""analyze_ev_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEihvtSCAtGeKYdzVzRH2liF1B6fDjM3
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load data
ev_data_path = '/content/EV_Dataset.csv'
ev_data = pd.read_csv(ev_data_path)

# Analyze EV Sales by State and Category
sales_by_state = ev_data.groupby('State')['EV_Sales_Quantity'].sum().sort_values(ascending=False)

sales_by_category = ev_data.groupby('Vehicle_Category')['EV_Sales_Quantity'].sum()

# Visualization - Sales by State and Category
plt.figure(figsize=(10, 6))
sales_by_state.head(10).plot(kind='bar', color='orange')
plt.title('Top States by EV Sales')
plt.xlabel('State')
plt.ylabel('EV Sales Quantity')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('ev_sales_by_state.png')
plt.show()

plt.figure(figsize=(10, 6))
sales_by_category.plot(kind='pie', autopct='%1.1f%%', startangle=140, colors=['lightgreen', 'gold', 'skyblue', 'lightcoral'])
plt.title('EV Sales by Vehicle Category')
plt.ylabel('')
plt.tight_layout()
plt.savefig('ev_sales_by_category.png')
plt.show()