# -*- coding: utf-8 -*-
"""analyze_charging_stations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIQ1-2rg2uh5HQLvq9YYeE16ISYnvkpJ
"""

import pandas as pd
import matplotlib.pyplot as plt

# Loading Data
charging_data_path = '/content/ev-charging-stations-india(in).csv'
charging_data = pd.read_csv(charging_data_path)

# Analyze Charging Stations by State
charging_by_state = charging_data['State'].value_counts()

# Visualization
plt.figure(figsize=(10, 6))
charging_by_state.head(10).plot(kind='bar', color='skyblue')
plt.title('Top States by Charging Stations')
plt.xlabel('State')
plt.ylabel('Number of Charging Stations')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('charging_stations_by_state.png')
plt.show()